# Generated by Django 4.2.5 on 2023-09-28 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import habit_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='profile.png', upload_to='profile_pictures/')),
                ('habits', models.CharField(max_length=200)),
                ('checkins', models.JSONField(default=habit_app.models.get_default_empty_list)),
                ('active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
